import React from 'react'
import { View, Text, StyleSheet } from '@react-pdf/renderer'

const styles = StyleSheet.create({
    footer: { position: 'absolute', bottom: 24, left: 24, right: 24, fontSize: 9, color: '#666' },
    small: { fontSize: 8, color: '#999', marginTop: 4 }
})

export default function InvoiceFooter({ meta }: any) {
    return (
        <View style={styles.footer} fixed>
            <Text>Thank you for your business. {meta?.companyName || 'Neelkanth Tiffin Service'}</Text>
            <Text style={styles.small}>Generated On: {meta?.generatedOn} • Generated By System</Text>
            <Text style={styles.small}>Support: {meta?.supportContact}</Text>
            <Text style={styles.small}>Page <Text render={({ pageNumber, totalPages }) => `${pageNumber} of ${totalPages}`} /></Text>
        </View>
    )
}
